export default [
    {
        path:'/main',
        name:'main',
        component:()=>import('./main.vue'),
        redirect:'/shop',
        children:[
            {
                path:'/shop',
                name:'shop',
                component:()=>import('./shop.vue'),
            },
            {
                path:'/mine',
                name:'mine',
                component:()=>import('./mine.vue'),
            },
            {
                path:'/cart',
                name:'cart',
                component:()=>import('@/views/Cart/cart.vue'),
            },
            {
                path:'/classify',
                name:'classify',
                component:()=>import('@/views/Classify/classify.vue'),
            },
        ]
    }
]