export default[
    {
        path:'/login',
        name:'login',
        component:()=>import('./login.vue')
    },
    {
        path:'/regist',
        name:'regist',
        component:()=>import('./regist.vue')
    },
    {
        path:'/phone',
        name:'phone',
        component:()=>import('./phone.vue')
    },
    {
        path:'/forget',
        name:'forget',
        component:()=>import('./forget.vue')
    },
]