export default[
    {
        path:'/cart',
        name:'cart',
        component:()=>import('./cart.vue')
    },
    {
        path:'/order',
        name:'order',
        component:()=>import('./order.vue')
    },
    {
        path:'/adress',
        name:'adress',
        component:()=>import('./adress.vue')
    },
    {
        path:'/editadress',
        name:'editadress',
        component:()=>import('./editadress.vue')
    },
    {
        path:'/updateadress',
        name:'updateadress',
        component:()=>import('./updateadress.vue')
    },
    {
        path:'/buy',
        name:'buy',
        component:()=>import('./buy.vue')
    }
]